apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
  - image: felixtran39/skaffold-example
  tagPolicy:
    userDefined:
      template: "{{.IMAGE_NAME}}:{{.FOO}}_{{.BAR}}"
      components:
      - name: FOO
        dateTime:
          format: "2006-01-02"
          timezone: "UTC"
      - name: BAR
        gitCommit:
          variant: AbbrevCommitSha
deploy:
  kubectl:
    manifests:
      - k8s-*
